openbazaar:
  image: openbazaar/server
  ports:
   - "4002:4002"

mongodb:
  image: mongo
  ports: 
    - "3500:27017"
  volumes:
    - ./data:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always
    
connextcms:
  build: .
  dockerfile: Dockerfile
  links:
    - mongodb
  ports:
    - "3000:3000"  # ConnextCMS serves website on this port
    - "9229:9229"  # Node v8 inspector runs on this port
  volumes:
    - ./theme:/home/connextcms/theme
    - ./plugins:/home/connextcms/plugins
    - ./public:/home/connextcms/public
  restart: always
    
